<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.IO.Actor" Version="0.44.0--ci.2" />
        <PackageReference Include="CK.IO.Workspace" Version="15.2.0--ci.3" />
    </ItemGroup>

</Project>
