<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.IO.Actor" Version="1.0.0--ci.2" />
        <PackageReference Include="CK.IO.Workspace" Version="16.0.0--ci.2" />
    </ItemGroup>

</Project>
